apiVersion: v1
kind: Service
metadata:
  name: payrolls-srv
spec:
  type: NodePort
  selector:
    app: payrolls
  ports:
    - name: payrolls
      protocol: TCP
      port: 3000
      targetPort: 3000
